version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: stunguard-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stunguard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    container_name: stunguard-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
